config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  #TODO: Later specify specific crud routes used
  resources :buckets do
    resources :subscribers, only: [ :create ]
  end
  resource :unsubscribe, only: [ :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "buckets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  include Notifications

  has_many :subscribers, dependent: :destroy
  has_one_attached :featured_image
  has_rich_text :description
  validates :title, presence: true

  after_update_commit :notify_subscribers, if: :is_completed?
end

app/models/bucket/notifications.rb
module Bucket::Notifications
  extend ActiveSupport::Concern

  included do
    has_many :subscribers, dependent: :destroy
    after_update_commit :notify_subscribers, if: :is_completed?
  end

  def is_completed?
    is_completed_previously_was === false && is_completed === true
  end

  def notify_subscribers
    subscribers.each do |subscriber|
      BucketMailer.with(bucket: self, subscriber: subscriber).is_completed.deliver_later
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :bucket
  generates_token_for :unsubscribe
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: %i[ show edit update destroy]

  def index
    @buckets = Bucket.all
  end

  def show
  end

  def new
    @bucket = Bucket.new
  end

  def create
    @bucket = Bucket.new(bucket_params)
    if @bucket.save
      redirect_to @bucket
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @bucket.update(bucket_params)
      redirect_to @bucket
    else
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    @bucket.destroy
    redirect_to buckets_path, notice: "Bucket was succesfully deleted"
  end
  private
  def set_bucket
    @bucket = Bucket.find(params[:id])
  end

  def bucket_params
    params.expect(bucket: [ :title, :description,  :featured_image ])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  allow_unauthenticated_access
  before_action :set_bucket

  def create
    @bucket.subscribers.where(subscriber_params).first_or_create
    redirect_to @bucket, notice: "You are now subscribed."
  end

  private

  def set_bucket
    @bucket = bucket.find(params[:bucket_id])
  end

  def subscriber_params
    params.expect(subscriber: [ :email ])
  end
end

app/controllers/unsubscribes_controller.rb
class UnsubscribesController < ApplicationController
  allow_unauthenticated_access
  before_action :set_subscriber

  def show
    @subscriber&.destroy
    redirect_to root_path, notice: "Unsubscribed successfully."
  end

  private

  def set_subscriber
    @subscriber = Subscriber.find_by_token_for(:unsubscribe, params[:token])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/buckets/_form.html.erb
<%= form_with model: bucket do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.rich_text_area :description %>
    </div>

    <div>
        <%= form.label :featured_image, style: "display: block" %>
        <%= form.file_field :featured_image, accept: "image/*" %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/buckets/edit.html.erb
<h1>Editar Bucket</h1>

<%= render "form", bucket: @bucket %>
<%= link_to "All buckets", buckets_path %>

app/views/buckets/index.html.erb
<h1><%= t ".title" %></h1>

<%= link_to "Crear un nuevo bucket", new_bucket_path %>

<div>
    <% @buckets.each do |bucket| %>
        <p><%= link_to bucket.title, bucket %></p>
    <% end %>
</div>

app/views/buckets/new.html.erb
<h1>Nuevo Bucket</h1>

<%= form_with model: @bucket do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_field :description %>
    </div>

    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/buckets/show.html.erb
<%= image_tag @bucket.featured_image if @bucket.featured_image.attached? %>
<% cache @bucket do %>
<h1><%= @bucket.title %></h1>
<div>
    <p><%= @bucket.description %></p>
</div>
<% end %>

<div>
    <%= form_with model: [product, Subscriber.new] do |form| %>
        <%= form.email_field :email, placeholder: "you@example.com", required: true %>
        <%= form.submit "Submit" %>
    <% end %>
</div>

<%= link_to "Edit bucket", edit_bucket_path(@bucket)%>
<%= link_to "All buckets", buckets_path%>
<%= button_to "Delete", @bucket, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bucketlist" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="notice"><%= notice %></div>
    <nav>
      <%= link_to "Home", root_path %>
      <%= link_to "Login", new_session_path unless authenticated? %>
      <%= button_to "Log out", session_path, method: :delete if authenticated?%>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>